//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ahorasi.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehiculosR
    {
        public int Id_Vehiculo { get; set; }
        public System.DateTime Fecha { get; set; }
        public string TipoVehiculo { get; set; }
        public string Color { get; set; }
        public string Placa { get; set; }
        public string Marca { get; set; }
        public Nullable<int> Id_Usuario { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
